
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace StreamRoar.Configs
{
public partial class Tables
{
    /// <summary>
    /// 导出测试表
    /// </summary>
    public TbTest TbTest {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbTest = new TbTest(loader("TbTest"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbTest.ResolveRef(this);
    }

    public System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.Type, object>> GetAllTables()
    {
        yield return new System.Collections.Generic.KeyValuePair<System.Type, object>(
            typeof(TbTest), TbTest);
    }
}

}

