
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace StreamRoar.Configs
{
/// <summary>
/// 导出测试表
/// </summary>
public partial class TbTest
{
    private readonly System.Collections.Generic.Dictionary<int, TestRow> _dataMap;
    private readonly System.Collections.Generic.List<TestRow> _dataList;
    
    public TbTest(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, TestRow>(n);
        _dataList = new System.Collections.Generic.List<TestRow>(n);
        for(int i = n ; i > 0 ; --i)
        {
            TestRow _v;
            _v = global::StreamRoar.Configs.TestRow.DeserializeTestRow(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, TestRow> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<TestRow> DataList => _dataList;

    public TestRow GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TestRow Get(int key) => _dataMap[key];
    public TestRow this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

