
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace StreamRoar.Configs
{
/// <summary>
/// 测试表的一行数据
/// </summary>
public sealed partial class TestRow : Luban.BeanBase
{
    public TestRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Value = _buf.ReadInt();
    }

    public static TestRow DeserializeTestRow(ByteBuf _buf)
    {
        return new TestRow(_buf);
    }

    /// <summary>
    /// 唯一编号，不可重复
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 测试名称，不可为空
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 测试数值
    /// </summary>
    public readonly int Value;
   
    public const int __ID__ = 242185160;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

